version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/var/lib/mongodb/data
  
  product-catalog-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mongo
