version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8087:8087'
    depends_on:
      - postgres
    environment:
      - POSTGRES_URI=postgresql://postgres:12345678@postgres:5432/postgres?sslmode=disable
